### PR TITLE
Thermodynamics

### PR DESCRIPTION
**Pull request by srmnitc**

### CODE REVIEW

**Comment by srmnitc** [comment]
@liamhuber ´melting_temperature´ notebook has our attempts at a While construct which runs the first iteration, and stops. Any help to get that fixed would be awesome! Thanks!

**Comment by liamhuber** [comment]
@srmnitc how long should it take to execute? I cloned to my local machine, and had to drop to two cores, but it's running for multiple minutes now -- is it silently hanging somewhere or just takes a while?

**Comment by liamhuber** [comment]
@srmnitc, I'm afraid I couldn't get the workflow to finish -- either I'm not being patient enough or it's just hanging. However, I replaced the body with something much simpler:

```python
@Workflow.wrap.as_macro_node
def RunFreeEnergy(
    self,
    inp,
    species,
    potential,
    temperature
):
    self.incremented_temp = increment_temperature(
        temperature,
        100
    )
    return self.incremented_temp
```

And then it works fine. I added a print statement inside `increment_temperature`, and I see the number of prints I expect and the result is perfectly consistent with `macro.provenance_by_execution`. So there appears to be nothing wrong with how you've written the while-loop, but somehow it's not playing nicely with your `RunFreeEnergy` -- can you double-check that `macro.free_energy.outputs.incremented_temp` is returning what you think? Given that the while-loop itself is returning an expected value, my guess is that this is returning a big enough number to correctly terminate the while condition.

**Comment by liamhuber** [comment]
Alright, I don't know why yours returned a single step, but I figured out why mine was hanging and it is working fine for me now.

The problem was that `UpdateTemperature` is mutating data, so `Initialize` was seeing that it had the exact same input as it already had in its cache, so instead of running it just returns existing output. This got me stuck in an infinite loop where the temperature in `RunFreeEnergy.step2a` keeps climbing but `RunFreeEnergy.step3` is always returning the same old temperature.

This can be solved by disabling caching in `RunFreeEnergy` with `wf.step3.use_cache = False`, or (probably the better route) by updating `UpdateTemperature` to be functional:

```python
@Workflow.wrap.as_function_node()
def UpdateTemperature(inp, temperature, make_copy=True):
    if make_copy:
        inp = InputClass(**asdict(inp))
    inp.temperature = temperature
    return inp
```

**Comment by srmnitc** [comment]
@liamhuber with your suggestion, this works very well! Thanks a lot.

**Review by liamhuber — APPROVED** [review]
Yeah, nice! I mean overall it looks good to me. Something that's been nice about this PR is starting to dig into the interplay between dataclasses and mutability (especially the potentially pernicious interaction with caching).

On that front, I see two places we might explore further here: first is exposing the entire input dataclass as a dataclass node; I think you're right to take the dataclass as input for the macro, but then in the notebook it might be nice to see input node > macro as a workflow. The other thing here is that for the while loop you do need to literally update the dataclass the user passes in -- right now I don't see a nice way of avoiding that -- but I think we can generalize what you do already to reduce code and make it useful for others in the same situation:

```python
from dataclasses import asdict
from pyiron_workflow import as_function_node
from pyiron_workflow.type_hinting import valid_value

@as_function_node
def UpdateDataclass(dc, field: str, value, make_copy=True, check_type=True):
    if check_type:
        field_type = dc.__class__.__dataclass_fields__[field].type
        if not valid_value(value, field_type):
            raise TypeError(
                f"Cannot set {dc.__class__.__name__} field {field} to {value} -- "
                f"expected type {field_type}"
            )
    if make_copy:
        dc = dc.__class__(**asdict(dc))
    setattr(dc, field, value)
    return dc
```

I also didn't go over things with a fine-toothed comb, but there's some polish (like replacing `wf.stepn` with physically meaningful names as Joerg suggested), and some workflow features you can lean on more heavily to tighten things up -- E.g., I don't think you need `increment_iteration` at all; in `WhileRunFreeEnergy` you should be able to leverage node injection to replace

```python
wf.increment_iteration = increment_iteration(iteration)
wf.increment_iteration.inputs.iteration = wf.increment_iteration.outputs.new_iteration
```

with

```python
wf.increment_iteration = iteration + 1  # injects an Add(obj, other) node
wf.increment_iteration.inputs.obj = wf.increment_iteration
# Makes a cyclic connection from the single "add" output to the "obj" input
```

Super fun to see the workflows used for something as powerful as this! Looks like things play relatively nicely with calphy in terms of interface too, the `Calculation` object seems like a nice balance of power and flexibility (some of the ASE calculator objects were much more of a headache when I was wrapping them...)

**Pull request merged**
